### ISSUE TITLE
Unexplained entry in pyproject.toml

### ISSUE THREAD

**Issue by captaincoordinates** [sparkgeo/stac-fastapi-indexed#135]
Unclear why the following section is in `pyproject.toml`

```toml
[tool.setuptools.packages.find]
where = ["src/"]
include = ["stac_fastapi.geoparquet"]

```
